version: "3"
services:

  #database

  LDBdatabase:
    image: linuxserver/mariadb:latest
    container_name: LDBdatabase
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=replacerootpwd
      - TZ=America/Vancouver
      - MYSQL_DATABASE=replacedb
      - MYSQL_USER=replaceuser
      - MYSQL_PASSWORD=replacepwd
    restart: always
    networks:
      - ldbbackend

  ldbredis:
    image: redis:alpine
    container_name: ldbredis
    restart: always
    networks:
      - ldbbackend

  #apps, will build to order

  ldb_processor_bc:
    container_name: LDBprocessor_bc
    build:
      context: ./
      dockerfile: dockerfile-bc
      args:
        - TZ=America/Vancouver
    user: "1002:1002"
    environment:
      - REDIS_IP=ldbredis
      - MYSQL_IP=replacesqlip
      - MYSQL_PORT=replacesqlport
      - MYSQL_DATABASE=replacedb
      - MYSQL_USER=replaceuser
      - MYSQL_PASSWORD=replacepwd
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    depends_on:
      - ldbredis
      - LDBdatabase
    networks:
      - ldbbackend
  ldb_processor_os:
    container_name: LDBprocessor_os
    build:
      context: ./
      dockerfile: dockerfile-os
      args:
        - TZ=America/Vancouver
    user: "1002:1002"
    environment:
      - REDIS_IP=ldbredis
      - MYSQL_IP=replacesqlip
      - MYSQL_PORT=replacesqlport
      - MYSQL_DATABASE=replacedb
      - MYSQL_USER=replaceuser
      - MYSQL_PASSWORD=replacepwd
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
      - /home/bibwsstaff/googledrive/OrderSubmission:/var/ordersubmission
    restart: always
    depends_on:
      - ldbredis
      - LDBdatabase
    networks:
      - ldbbackend
  ldb_processor_ar:
    container_name: LDBprocessor_ar
    build:
      context: ./
      dockerfile: dockerfile-ar
      args:
        - TZ=America/Vancouver
    user: "1002:1002"
    environment:
      - REDIS_IP=ldbredis
      - MYSQL_IP=replacesqlip
      - MYSQL_PORT=replacesqlport
      - MYSQL_DATABASE=replacedb
      - MYSQL_USER=replaceuser
      - MYSQL_PASSWORD=replacepwd
    volumes:
      - /home/bibwsstaff/ldbinvoice:/var/ldbinvoice
    restart: always
    depends_on:
      - ldbredis
      - LDBdatabase
    networks:
      - ldbbackend
networks:
  ldbbackend:
